# Generated by Django 4.1.7 on 2023-03-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(default="Enter Slug here", unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(blank=True, default="Enter content here", null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.TextField(default="Enter title here"),
        ),
    ]
